### ISSUE TITLE
Windows/npm installed - First line of X not URL

### ISSUE THREAD

**Issue by jakenuts** [tebelorg/TagUI#28]
1. Installed TagUI using npm 
2. Set Path to the src folder
3. tagui mytest.gui chrome

Result is always "cannot understand step http://mysite.com" and "first line not URL". 
I also used one of the test files (Yahoo) and got a similar error.

**Comment by kensoh** [comment]
Hi @jakenuts thanks for making this bug report!

I tested on Windows 10 but without a Node environment. To try to isolate the cause, can you try to unzip the packaged installation to c:\tagui after that from command prompt go to c:\tagui\src folder and run tagui samples\1_yahoo ?

Below is the packaged installation URL for Windows (the one listed in the Setup section). https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Windows.zip

I had also looked through the code didn't find any clues why that portion of URL detection will break. Btw, I assume you are running within the normal Windows command prompt, not Cygwin or other Linux-env within Windows.

**Comment by jakenuts** [comment]
Thanks! The zipped version worked exactly as expected. I dug a bit in and found that line_number was 36 instead of 1 for the first line in my test file. It turns out this had to do with creating the test file in Visual Studio 2017 which saved it with an encoding that inserted BOF junk into that line. Still not what the encoding is that causes the issues but opening it in Sublime and saving as UTF-8 fixed the issue. Alternately notepad and Ansi encoding. Oy.. so sorry to trouble you.

**Comment by kensoh** [comment]
Hi @jakenuts I see, I understand now.. No probs at all I appreciate that users raise bug reports so that the tool can be improved, otherwise I cannot by myself validate all possible use cases.

Yeah the Visual Studio auto-adding of that header can mess up with other downstream apps. This VS plugin may be useful if it's something you want to remove automatically -

https://marketplace.visualstudio.com/items?itemName=SergeyVlasov.FixFileEncoding
