### ISSUE TITLE
Q: Run a suite of tests?

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#31]
HI @kensoh,

Is it possible to run all flows in a directory?
Or run a collection a flows after each other with 1 command?

Example:
`
./src/tagui ./src/samples/* firefox test
`

Or is it best to put them in 1 script file where they are listed one by one

Bash script >> with the following

```
./src/tagui ./src/samples/1_yahoo firefox test
./src/tagui ./src/samples/2_twitter firefox test
./src/tagui ./src/samples/3_github firefox test
./src/tagui ./src/samples/4_conditions firefox test
```

**Comment by kensoh** [comment]
Hi @thim81 thanks for raising this question. It's best to handle using a bash script as you showed above. Alternatively, the script can be as follows. It can work for cases where the file names are flow001, flow002, flow003 and calling ```run_suite flow???``` will iterate through the files. But it won't work for * because after the first run * will start to run the generated files (.js .log etc).

**run_suite**
```bash
#!/usr/bin/env bash
for flow in "$@"
do
    tagui "$flow" test
done
```

Also, handling wildcards in the main runner tagui and tagui.cmd will break. Because in the runner, having wildcards will be trying to do action1 for all the filenames, action2 for all the filenames, action3 for all filenames. Instead of file1 action1, action2, action3 then file2 action1, action2, action3. This sequential handling is important to deal with the various integrations of TagUI, such as Chrome/Sikuli and features such as handling the datatables for batch automation of different test cases.

**Comment by thim81** [comment]
@kensoh 

Very clear and logic.

To resolve the issue with the `for` logic and generated files, could be handled by adding a check for specific extensions.

`Automation flow filename can have no extension, .gui or .txt file extension`

Lets assume we give the flows the .gui extension, then the following would work:

```
for flow in "$arg"/*.{txt,gui} ;
do
    tagui "$flow" test
done
```

**Comment by kensoh** [comment]
Thanks for sharing @thim81 :smile: It might still break unless TagUI code is changed, in the sense flow.txt generates flow.gui.log, flow.gui.js etc. I don't know what I was thinking then, probably to minimize potential edge issues from removing extension and appending the extension to the flow filename.

**Comment by kensoh** [comment]
Thanks for sharing @thim81 :smile: that's true that should work even with generated .log .js files.
