### ISSUE TITLE
BUG - Different behaviour for assertSelectorHasText

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#36]
When running assertSelectorHasText on body to verify if a text is present, the script on Firefox PASS but on Chrome it FAILS

Example:
```
http://tebel.org/gist/about_tebel

test.assertSelectorHasText(tx('body'), "Tebel.Automation",'Check if has keyword');
```

Firefox: `./src/tagui ./sample/test_body firefox test`

`PASS Check if has keyword`

Chrome: `./src/tagui ./sample/test_body chrome test`

```
AIL Check if has keyword
#    type: assertSelectorHasText
#    file: /Sites/localhost/tagui/sample/test_body.js
#    subject: false
#    selector: "body"
#    text: "Tebel.Automation"
#    actualContent: ""
[info] [phantom] Step anonymous 3/4: done in 1462ms.
# http://tebel.org/gist/about_tebel - About Tebel
[info] [phantom] Step anonymous 4/4: done in 1666ms.
[info] [phantom] Done 4 steps in 1666ms
PASS /Users/tim/Sites/localhost/tagui/hyperlane/test_body (1 test)
FAIL 1 test executed in 1.487s, 0 passed, 1 failed, 0 dubious, 0 skipped.
```

**Comment by thim81** [comment]
Additional, I use assertSelectorHasText to check if a text exists in the page, perhaps there are better checks for this?

I looked in the CasperJS documentation and Google but none of them gave me a working solution.

**Comment by kensoh** [comment]
Hi @thim81 yes this is expected. The testing framework for CasperJS is not usable with running on Chrome as CasperJS does not support Chrome at the moment. I added that note in the testing section, and also another note at the start of developers reference with a recommended list of open-source tools that can be used for test automation. This is because there are many established tools that can do a great job at specifically testing. https://github.com/tebelorg/TagUI#testing

**Comment by kensoh** [comment]
For CasperJS testing framework if you want to check text for the page body you can consider using this.assertTextExists() - http://docs.casperjs.org/en/latest/modules/tester.html#asserttextexists

**Comment by kensoh** [comment]
Actually CasperJS testing framework is expressive and really good at that time when it was introduced. My only guess is due to other frameworks such as NightmareJS moving to the more popular Electron browser, and that being centrally developed instead of having a plug-and-play model, over time I don't think the testing framework become the leading approach for developers / test automation engineers.

**Comment by kensoh** [comment]
This issue can probably be closed, I think I can update the readme to make it more clear. There are some updates to improve readme clarity from a couple from your closed issues as well.
