### ISSUE TITLE
Q: Get API_JSON data in variable

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#41]
I'm trying to open a link that I get from an API reponse, but I'm missing something.

flow api 

```
http://demo3796957.mockable.io/test

//api_config.header[0] = 'Header1: value1';
api http://demo3796957.mockable.io/test
echo api_result
echo 'Link - ' + api_json.link

{
    '+api_json.link+'
}

```

`./src/tagui ./sample/test_api firefox test`

Show the following output

```
ERROR - [LINE 11] cannot understand step '+api_json.link+'
ERROR - automation aborted due to above
```

**Comment by kensoh** [comment]
Yes this is expected, TagUI works by letting users convey their intention through various steps + JS code as needed. It will check if the line starts with http:// or https:// to detect that user wants to access an URL. In this case '+api_json.link+' is a variable and it doesn't convey that intention, so it throws error. It should work if the URL is broken down to http://'+api_json.link+' etc where api_json.link is github.com/tebelorg/TagUI instead of https://github.com/tebelorg/TagUI.

**Comment by kensoh** [comment]
Closing this issue for now, added some note on the other issue.

"Adding on, for eg in JavaScript, we can't really define a variable as a string JS statement, then type that variable on an empty line by itself to execute the statement. JS can use eval. For TagUI the parsing happens before the execution, when natural-language-syntax converts into JS code. Such replacements will work if they are provided from data tables, as it is still within control during parsing."

For above scenario and the data_test variable scenario, as long the http:// or https:// is not made part of the variable contents it should work when concatenated back. So that TagUI recognizes user intention is calling an URL when http://'+variable+' is used.

**Comment by thim81** [comment]
I solved it like this but this feels very dirty, so perhaps I'm missing a better way

```
https://github.com/

//api_config.header[0] = 'Header1: value1';
api http://demo3796957.mockable.io/test
echo api_result
echo 'Link - ' + api_json.link

link = api_json.link.replace('https://github.com/','');
echo link

{
  https://github.com/'+link+'
}
```
