### ISSUE TITLE
Issue with popups

### ISSUE THREAD

**Issue by hitkicker** [tebelorg/TagUI#49]
I'm a newbie so I have a newbie question: how do you handle popups in TagUI?

I'm attempting to create automated tests for an application my company is developing. Some of the functions employ "are you sure" type popups. When this happens TagUI simply sits waiting; it can't "see" the popup and it doesn't throw an error message.
The Chrome extension doesn't record anything when I use it to try to record responding to the popup.
I see that there is a popup command but I can't figure out how to use it. Can someone provide an example?
I'm using Chrome 60 in Windows 7.

**Comment by kensoh** [comment]
Hi @hitkicker welcome to GitHub :) I've updated readme to add example of limitation of the Chrome Extension. It's based on Resurrectio project and Zope recorder, and I'm afraid it can't capture frames or popup windows. There's also other limitations such as can't record mouse movements.

Can you show a sample website where this happens and steps to replicate this issue? If it is a 'popup' that is part of the HTML page, some manual editing may work. For the popup step, it is for handling new tabs of popup windows, so that you can interact with elements on the new tab, for example - 

```
popup string_to_look_for_in_popup_url
{
click abc
enter xyz as text
do something else
}
```

Adding on for test automation, I recommend checking out [this awesome list](https://github.com/atinfo/awesome-test-automation) which has many tools with mature ecosystems. And if you like to experimenting new things, check out [pupeteer project](https://github.com/GoogleChrome/puppeteer). Google Chrome team just launched it last week but its API looks great.
