### ISSUE TITLE
Read a file to a variable

### ISSUE THREAD

**Issue by zjevik** [tebelorg/TagUI#56]
Would it be possible to add a step to load the context of a file to a variable?

**Comment by kensoh** [comment]
Hi @zjevik for the time being you can use the following to load a file into variable. filename can be a full path or a relative path or just the filename if the file is in same directory as the flow file.

```js
var fs = require('fs'); file_content = fs.read(abs_file('filename'));
```

This sounds like a good shortcut and feature to add, I'm thinking whether it is better to create a new load step or to combine it with read step. It is possible to autocheck filename if combined with read. That makes it one less step for users to know. But this creates problems if an element identifier happens to be the same name as a filename which exists on the OS.

**Comment by kensoh** [comment]
After thinking through, decided to put this on hold. The rationale is there is already [datatables](https://github.com/tebelorg/TagUI#datatables) which enables easy input of dynamic values and multiple datasets. Also, if the file contents is big and has special formatting, just reading it into the variable may not work, may still need to do other formatting using code (escaping quotes) or other processing. In that case, saving a line of code above doesn't help much. Lastly, enabling that new step may lead to another user suggestion to read a file row by row or by streaming. That may be too out of scope for TagUI, which focuses more on simulating the actual user interaction with the browser, while other custom coding can be done directly using JavaScript.

Closing issue for now but do let me know your thoughts or if above 1-liner could not work for you!

**Comment by zjevik** [comment]
@kensoh The one liner works flawlessly.

I totally understand your reasoning. Let me tell you what are my intentions for reading the file.
I would like my program to enter some text in a field. This text has to be different base on the week of current month and the day of the week. I could do this by two switch statements but the source file would be too big. Instead, I have files with names {week}_{day}.txt with the text and I load its content to a variable.

After reading the sample on datatables I wasn't able to figure out how I could do this. Looking back I could try to use repositories but I made it work with the one liner you posted here :)

**Comment by kensoh** [comment]
I see, thanks @zjevik for sharing, it sounds like you have made an elegant and easy to maintain implementation! :)

Yeah datatables are meant for repeated runs of the same flow using different data. Your use case is a single run using different data. Repositories might be possible but all the combinations would have to be defined in the flow file.

The text substitution happens before a flow file starts execution, so that each new iteration is treated like a fresh run using a new set of data without awareness that it is looping through a dataset. The main reason for this design, besides isolation of successive runs and clearing memory for stability, is such that it favors creation of sophisticated substitutions involving TagUI steps, not just data. For eg the type email [repository example](https://github.com/tebelorg/TagUI#repositories). The words have to be replaced before TagUI parses the intentions into JavaScript, thus referencing repositories isn't done within actual execution.

Your use case highlights something that can't be done with repository -> loading a filename or data reference that is formed dynamically. I'll have to lookout for this and reconsider implementing if it impacts many people. Having seen CasperJS [test assertions](http://docs.casperjs.org/en/latest/modules/tester.html) (> 30 of them) while comprehensive, it can be paralyzing to see and decide how to use.

**Comment by kensoh** [comment]
Added load step to improve ease of chaining / integrating. [Committed to master](https://github.com/tebelorg/TagUI/archive/master.zip) with below comments - 

- add load step to load file content into variable
- usage - load filename to variable_name
- this allows easier chaining of automation flows, by making it easy to use files as inputs, other than using input parameters p1 to p9
- eg from other applications to write to files to be used as inputs or from an upstream TagUI flow to write to files to be used as inputs
- this also allows a dynamic filename to be used for eg load '+some_variable_for_filename+' to variable_name
- streaming or reading line by line is out-of-scope but can be implemented by users using standard JavaScript code
