### ISSUE TITLE
Modal with Hidden Field and Verification Token Prevents Access to Form Attribute Fields

### ISSUE THREAD

**Issue by TMM21042** [tebelorg/TagUI#57]
My tagui script to sign-in (login) to a website fails and returns an error because it cannot find the x-path attribute that I have defined in the automated flow (i.e., email address field).  The attribute is a field on a modal login form.  Upon inspection, I see that the modal form includes a hidden input field that is named "request verification token" in addition to visible fields for email and password.  Since manual entry works fine, I assume the hidden field exists to create a response before the remaining two fields (email and password) can be found and used by the script, but I am not sure how this works.  First question: what is the purpose of hidden fields such as this?  Second, is there a technique to pass the verification test automatically in a tagui flow? Lastly, do other tools exist that would allow automation when there are hidden fields such as this?  Thanks for any advice you can share.

**Comment by kensoh** [comment]
Hi @TMM21042 can you share more which website and what steps you are doing in your flow?

Some websites intentionally block automated browsers (such as PhantomJS and others). It is an ongoing race for some website owners to deploy technologies that can detect if a browser is not a human user and blocks it, versus people who try to overcome these blocks. In general I won't try to overcome that, because it never ends and isn't constructive.

An idea to check is try running in chrome mode (run tagui with chrome option), to see if using chrome works. Then try running with headless option (chrome headless mode), to see if headless chrome works instead of the default phantomjs. **Do note to close your chrome tabs before running** as tagui will restart chrome in order to create websocket connection (this will kill all existing chrome sessions).

Some other tips is use the live step to do live debugging. You can then use show page / read page / save page to check status of web page DOM to test your interaction live with the website.

I'm not sure of other tools. Depending on how the block happens, there are different ways. For eg, if block is done by IP address recognition, some automation folks uses IP pool service providers to enable IP proxy, so that websites thinks that you are different users accessing from different IPs.

**Comment by kensoh** [comment]
Hi Tom, I've received your email of the flow script and the website you are automating. As there's no sensitive info, I'll reply here so other users with similar issues can benefit.

Yes it looks like the website is blocking access by making an explicit verification token. It can be done in different ways, visually obvious ways such as captcha to enter text base on images, selecting images base on description, click a check-box in a human-like way, or other invisible methods such as browser fingerprinting.

You can try the above suggestion - during running of your flow file, there will be a step which fails due to the verification token required. ***Try adding a live step before that step so that you can do debugging live***, using steps such as show page / read page / save page to see the webpage HTML. By seeing the webpage HTML changes live as you interact live with the webpage, you can try to figure out if the verification is something you can simulate (if website is serious to block I'll think probably can't).

Also, try above suggestion to ***run using chrome option to see if it works when running in Chrome browser***. And headless option to run in invisible Chrome browser. That may help if the verification is specifically targetting PhantomJS invisible browser and not Chrome.

**Comment by kensoh** [comment]
Closing this for now as it is due to website explicitly blocking automated browsers. Above suggestions can be attempted but I generally don't recommend trying to beat those captcha or anti-robot websites. Besides not respecting website owner wishes, it is a never-ending race and would be a waste of time.
