### ISSUE TITLE
How to select "- nothing -" from dropdown input

### ISSUE THREAD

**Issue by rouilj** [tebelorg/TagUI#58]
Hello:

I have an select input named @group0 and I need to select the option: 

    <option value="">- nothing -</option>

I have tried selecting this using:

  select @group0 as ""
  select @group0 as - nothing -
  select @group0 as "- nothing -"
  select @group0 as -%20nothing%20-

  nothing=- nothing -
  select @group0 as "nothing"
  
no joy. I can select the:

  <option value="id">id</option>

using 

  select @group0 as id

so what's the magic and where is the documentation I missed reading....

Thanks.

-- rouilj

**Comment by kensoh** [comment]
Hi @rouilj this is not supported and is expected behavior. Your scenario is trying to select an option dropdown that has no value assigned to it. CasperJS does not support selection of drop down options, so a [custom solution from StackOverflow](https://github.com/tebelorg/TagUI/issues/11#issuecomment-282513221) is used. In the custom solution, the value attribute of the option is used as it uniquely identifies that option.

In this case, it looks like the webpage has a non-standard design by having options without values. If you still would want to try, you can edit the file tagui_header.js and change the 2 occurences `opt.value.indexOf` to `opt.textContent.indexOf`. This changes the behavior to look for the text content property of the option instead of the value property.

After that you can try again with `select @group0 as - nothing -`. I assume that `- nothing -` is the text you see on that option and not something you added above to demonstrate that it is blank text. I won't modify default TagUI behavior to look at textContent instead as checking value is a more robust way and the change shouldn't be made to make edge cases work at expense of majority of use cases.

**Comment by rouilj** [comment]
Hi @kensoh 

There is a value assigned to the option. It's the empty/null string which is why I expected

select @group0 as ""

would work.

This web page follows a mechanism I have seen in many other pages, e.g. drupal and many answers to how to mark up a placeholder element in select controls. It allows the user to not choose an option from
the select list and submit the form. This results in a null state (or on some browsers the select field is
not sent) for the select field indicating that it is unset.

-- rouilj

**Comment by kensoh** [comment]
I see, you mean you want to 'unselect' a dropdown option to select the blank / default option.

**Solution to select empty option**

```
http://www.seleniumeasy.com/test/basic-select-dropdown-demo.html
blank = ""
click select-demo
select select-demo as Tuesday
wait
snap page
select select-demo as '+blank+'
wait
snap page
```

**Details why above works**

By default TagUI checks the value parameter to make sure user doesn't miss that out even before running the flow. There are also many other checks and corresponding help message on the flow script before running, so that user won't waste time running the flow and then get into some error when it can be corrected before running. So entering `select element as ` will trigger error message.

Also, TagUI default context is a natural language like syntax. So by default, text variables do not need quotation marks. Typing `select element as ""` will be interpreted as selecting the option with value of 2 double quotes "". The above website example works as '+variable_name+' can be used in places where text is expected to use variables. And above tries to select the option with an empty value.

The '+variable_name+' thing to access variables is done in exchange for text not having to be enclosed in single or double quotes in most TagUI steps, with bias for a natural language like syntax.

**Comment by kensoh** [comment]
Adding on to above workaround, committed to [master](https://github.com/tebelorg/TagUI/archive/master.zip) a more intuitive way to unselect option with commit comments. So that `select element as [clear]` will unselect by choosing blank value option.

- new use case of selecting empty option to ‘unselect’ option
- in issue #58 a workaround uses blank variable to do that
- but that is non-intuitive, adding this so following works
- tested to work in default mode or chrome mode
- select element as [clear]

Following tested to work in default phantomjs mode and also chrome mode. Outstanding is updating readme on next packaged release, together with other changes since the last packaged release. The master link above can be downloaded to overwrite existing installation to use immediately.

```
http://www.seleniumeasy.com/test/basic-select-dropdown-demo.html
click select-demo
select select-demo as Tuesday
wait
snap page
select select-demo as [clear]
wait
snap page
select select-demo as Friday
wait
snap page
select select-demo as [clear]
wait
snap page
```

**Comment by rouilj** [comment]
Thanks for the quick turnaround. the blank variable trick worked fine. The screenshot shows
what I expected. I look forward to the next release and I can [clear] up the code 8-).

**Comment by kensoh** [comment]
You're welcome Rouilj, you can also download current [master version](https://github.com/tebelorg/TagUI/archive/master.zip) to overwrite your existing installation and use the [clear] keyword right away. Due to different dependencies binaries for different OSes, TagUI Github repo can't include them. But unzipping over existing packaged release works.
