### ISSUE TITLE
Nested code blocks

### ISSUE THREAD

**Issue by zjevik** [tebelorg/TagUI#59]
Hi,

I tried to nest code blocks but I always get the error "missing } after function body".

The code I try to run is essentially like this:

for (i = -3; i < 5; i++)
{
	if (i > 0)
	{
		echo "i =  " i
	}
}

Thanks!

**Comment by kensoh** [comment]
Hi @zjevik the short answer is even writing nested loops manually for CasperJS / JavaScript form is challenging, given the different combinations of nests (for, while, if, popup, frame, etc).

So along the way the design prioritizes major use cases for eg nested for loops and letting frame and popup work in for loop to access elements within a frame or in a new popup window. Instead of trying to cover all possible combinations of nested code blocks.

In this case, write the if statement without the braces. Both the examples below works, first one is in JavaScript syntax, second one is in natural language for the conditions.

**javascript conditions**
```
http://tebel.org/index_mobile.php
for (i = -3; i < 5; i++)
{
if (i > 0)
echo "i = " i
}
```

**natural language conditions**
```
http://tebel.org/index_mobile.php
for i from -3 to 4
{
if i greater than 0
echo "i = " i
}
```

---

I almost left out another workaround, you can also use below approach. By using js step, it explicitly tells TagUI to treat that line as a pure JavaScript line. So it won't try to do post-processing for nests.

```
http://tebel.org/index_mobile.php
for (i = -3; i < 5; i++)
{
if (i > 0)
js {
echo "i = " i
js }
}
```

---

I won't have laptop access for coming week, if you encounter cases which the conversion doesn't work seamlessly and can't be solved by js step approach, you can try the manual way - editing the generated .js file and then casperjs flow.js to run your edited version.

It's not straightforward as we have to factor in the IIFE design pattern in order to access the for loop variables within the block, and in general multiple levels JavaScript code blocks are hard to write. And the code block structure requirements for a for loop block and if block is different. Nevertheless, editing manually may still save a lot more time than writing a full CasperJS script from scratch.

I'll treat this as a limitation, a program will probably require higher level cognitive thinking to interpret all possible nested code block structures into matching CasperJS JavaScript code blocks, especially when the resulting code blocks are different in different contexts and combinations of nests.

**Comment by zjevik** [comment]
Thanks @kensoh. Continuing developing my code, I found that the problem with nested code blocks is only one half of the story. When I try to implement the solution with 
js {
js }

my code didn't run. I pinpointed the problem to implementation of wait function in casper. The following code will not run since you cannot have nested block with wait function inside:

```
http://tebel.org/index_mobile.php
for (i = -3; i < 5; i++)
{
	if (i > 0)
	js {
		echo "i = " i
		wait 1
		echo "i = " i
	js }
}
```

The workaround I came with (using [stackoverflow](https://stackoverflow.com/a/37530788)) is the following code:

```
http://tebel.org/index_mobile.php

function waitNseconds(n) {
js 	var seconds = new Date().getTime() / 1000;
js  var time_now = seconds;
js  while ((time_now + n) > seconds)
js  {
js      seconds = new Date().getTime() / 1000;
js  }
js }

for (i = -3; i < 5; i++)
{
	if (i > 0)
	js {
		echo "i = " i
		js waitNseconds(2)
		echo "i = " i
	js }
}
```

**Comment by kensoh** [comment]
@zjevik I see, yeah TagUI will expand the click step out to a CasperJS block which includes auto-waiting for the element, showing error message after timeout, and clicking on it if found. The custom structure above { breaks the CasperJS code block. You can try either of the 2 ways below.

First way simply write the CasperJS statement directly without using click step. This means there is no auto-wait for the element to appear and the error-handling. If you are not familiar with CasperJS statements, the `this.click(tx('LINKEDIN'));` can be found by seeing the generated .js file.

```
http://tebel.org/index_mobile.php

for (i = -3; i < 5; i++)
{
        if (i > 0)
        js {
                echo "i = " i
                js sleep(2000)
                this.click(tx('LINKEDIN'));
                echo "i = " i
        js }
}
```

Second way is use multiple if statements such as below. It returns the auto-wait and error-handling. By the way there's already a sleep(ms) function defined in TagUI which you can use like above example.
```
http://tebel.org/index_mobile.php

for (i = -3; i < 5; i++)
{
        if (i > 0)
                echo "i = " i
        if (i > 0)
                click LINKEDIN
        if (i > 0)
                echo "i = " i
}
```

**Comment by kensoh** [comment]
[Commit to master](https://github.com/tebelorg/TagUI/archive/master.zip) with following comments - 
- more background details at issue #59
- add support for edge / use case raised
- supporting if block within for loop block
- pass current positive test set
- but may break other use cases
- address accordingly as it comes

You can use it right away by overwriting with above master link. Below works now. Made a small change in code that solves this without failing current test set. It might break other edge cases, if that happens may have to roll-back this change and improve the test cases. Thanks for raising this!
```
http://tebel.org/index_mobile.php

for i from -3 to 4
{
        if i greater than 0
        {
                echo "i = " i
                wait 2 seconds
                click LINKEDIN
                echo "i = " i
        }
}
```
