### ISSUE TITLE
"Chrome" option does not work anymore

### ISSUE THREAD

**Issue by Algram** [tebelorg/TagUI#60]
Hello,
after an Update to the latest Versions of Chrome and chromedriver `61.0.3163` when I pass the option `chrome` on the command line. It only opens a new tab in Chrome, but then just stops. There is no error message.

Thanks for your help!

**Comment by kensoh** [comment]
Thanks @Algram for raising this! It actually still works for me. I'm running the same Chrome version on macOS. Below is the sample flow and the run results. A Chrome browser opens up, navigates to the page and saves the screenshot.

```
http://tebel.org/index_mobile.php
wait 3.45 seconds
snap page
```

```
TA:Desktop kensoh$ tagui gc chrome

START - automation started - Tue Oct 17 2017 15:16:44 GMT+0800 (+08)
http://tebel.org/index_mobile.php - Tebel.Automation

wait 3.45 seconds
snap page

http://tebel.org/index_mobile.php - Tebel.Automation
FINISH - automation finished - 6.0s
```

**Comment by Algram** [comment]
Thanks for the quick reply. For me (on Linux, Fedora 26) you exact same script does not work. I only need the prepackaged zip, correct? I do not need any other packages?

**Comment by kensoh** [comment]
That's interesting, from your issue description above it sounds like it was working for you with this setup before your Chrome is upgraded. Yes, for Linux just use the packaged installation for Linux.

https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Linux.zip

1. For TagUI integration with Chrome, there is a tagui_chrome.log file in tagui/src directory. You can check and paste the error messages here if there is any, to see what can be checked further. This is probably a difficult issue to troubleshoot because I don't have a Linux laptop on my end to replicate.

2. The expected behavior should be to kill Chrome and restart it. This is required in order to establish a web socket server in Chrome for communication. It sounds like Chrome didn't restart? The default command and process it looks for to kill and restart is `google-chrome`. Is that the command and process name for your Fedora?

**Comment by Algram** [comment]
The process name is `chrome` and the command to start is `google-chrome`. Yes it worked yesterday. Although Chrome did not restart or close after the tests. In fact I need Chrome to stay open after the tests are finished.
It may also be that this is not a problem of the new Chrome version, but that no Websocket Connection can be established? The Log-Files you mentioned are empty and there is not a single error.

**Comment by kensoh** [comment]
This is strange, the assumption is the process name and the command to run is the same name. So at the start of src\tagui file there is a setting for user to define, and error message to show if command not found.

You can try edit the file src\tagui -
there is 2 occurrences of `pkill $chrome_command;` change it to `pkill chrome;` and maybe remove the 2nd occurrence if you don't want it to be killed after running. It's designed to kill-run-kill so that each iteration starts fresh.

**Comment by Algram** [comment]
Alright, so is there another option to connect to the websocket, without having to kill and restart chrome currently?

**Comment by kensoh** [comment]
It sounds like maybe there is some locked process that prevented the killing. If you want to debug, you can try killing by command line `pkill chrome` to see if that works, before updating src\tagui file.

I'm afraid not, the only way to talk to Chrome is through a web socket connection by enabling that explicitly on launch. If it is not restarted to start a web socket connection, there isn't even an entry point for TagUI to start controlling Chrome.

Unless your Chrome you already start it with `--remote-debugging-port=9222 about:blank` when you first launch it manually. Then maybe it will work. But after the first iteration it will stop working as that page entry point would have been navigated to somewhere else.

**Comment by Algram** [comment]
So I removed the second occurrence of the `pkill`-Command, but Chrome is still being closed after the test. Any ideas?

**Comment by kensoh** [comment]
No idea what is the issue facing your use case, but TagUI is designed to work with auto-killing Chrome to ensure stable environment for iterations (batch run)

You can also try downloading the latest version of TagUi and use the speed option to see if that helps. That option prevents auto-killing of Chrome after each iteration.
